SELECT
    tl.resource_type AS ResourceType,
    tl.resource_database_id AS DatabaseID,
    DB_NAME(tl.resource_database_id) AS DatabaseName,
    tl.resource_associated_entity_id AS AssociatedEntityID,
    OBJECT_NAME(p.object_id) AS LockedTable,
    tl.request_mode AS LockType,
    tl.request_status AS LockStatus,
    wt.blocking_session_id AS BlockingSessionID,
    bs.session_id AS BlockingSessionID,
    bs.login_name AS BlockingSessionLoginName,
    bs.host_name AS BlockingHostName,
    bs.program_name AS BlockingProgramName,
    bs.status AS BlockingSessionStatus,
    bs.wait_time AS BlockingWaitTime,
    bs.last_wait_type AS BlockingWaitType,
    bs.wait_type AS BlockingWaitTypeDescription,
    bs.wait_resource AS BlockingWaitResource,
    bs.open_tran AS BlockingOpenTransaction,
    bs.cpu_time AS BlockingCpuTime,
    bs.memory_usage AS BlockingMemoryUsage,
    bs.reads AS BlockingReads,
    bs.writes AS BlockingWrites,
    bs.logical_reads AS BlockingLogicalReads,
    bs.text_size AS BlockingTextSize,
    bs.lock_timeout AS BlockingLockTimeout,
    bs.transaction_isolation_level AS BlockingTransactionIsolationLevel,
    bs.granted_query_memory AS BlockingGrantedQueryMemory,
    bs.execution_context_id AS BlockingExecutionContextID,
    bs.scheduler_id AS BlockingSchedulerID,
    bs.task_address AS BlockingTaskAddress,
    bs.blocking_session_id AS BlockingSessionID,
    bs.wait_duration_ms AS BlockingWaitDurationMS,
    bs.transaction_id AS BlockingTransactionID,
    bs.request_id AS BlockingRequestID,
    bs.open_transaction_count AS BlockingOpenTransactionCount,
    bs.transaction_count AS BlockingTransactionCount,
    bs.encryption_options AS BlockingEncryptionOptions,
    bs.connection_id AS BlockingConnectionID,
    bs.is_user_process AS BlockingIsUserProcess,
    bs.is_system_process AS BlockingIsSystemProcess,
    bs.client_net_address AS BlockingClientNetAddress,
    bs.client_tcp_port AS BlockingClientTcpPort,
    bs.end_point_id AS BlockingEndPointID,
    bs.database_id AS BlockingDatabaseID,
    bs.database_name AS BlockingDatabaseName,
    bs.database_principal_id AS BlockingDatabasePrincipalID,
    bs.user_id AS BlockingUserID,
    bs.login_time AS BlockingLoginTime,
    bs.is_user_process AS BlockingIsUserProcess,
    bs.session_id AS BlockingSessionID,
    bs.execution_context_id AS BlockingExecutionContextID,
    bs.scheduler_id AS BlockingSchedulerID,
    bs.task_address AS BlockingTaskAddress,
    bs.task_state AS BlockingTaskState,
    bs.open_transaction_count AS BlockingOpenTransactionCount,
    bs.transaction_count AS BlockingTransactionCount,
    bs.transaction_isolation_level AS BlockingTransactionIsolationLevel,
    bs.connection_id AS BlockingConnectionID,
    bs.client_net_address AS BlockingClientNetAddress,
    bs.client_tcp_port AS BlockingClientTcpPort,
    bs.end_point_id AS BlockingEndPointID,
    bs.database_id AS BlockingDatabaseID,
    bs.database_principal_id AS BlockingDatabasePrincipalID,
    bs.user_id AS BlockingUserID,
    bs.login_time AS BlockingLoginTime
FROM
    sys.dm_tran_locks AS tl
    JOIN sys.partitions AS p ON p.hobt_id = tl.resource_associated_entity_id
    JOIN sys.dm_exec_requests AS wt ON tl.request_session_id = wt.session_id
    JOIN sys.dm_exec_sessions AS bs ON wt.blocking_session_id = bs.session_id
WHERE
    OBJECT_NAME(p.object_id) = 'YourTableNameHere'
ORDER BY
    bs.session_id;
